language: rust
dist: bionic
rust:
  - nightly
addons:
  apt:
    packages:
      - qemu
      - xorriso
      - grub
cache:
  - apt
  - directories:
    - toolchain
before_install:
  - rustup component add rust-src
  - rustup target add wasm32-wasi
  - cargo install cargo-xbuild
install:
  - cd toolchain && ./setup_cross_binutils.sh && cd ..
script:
  - ./run_tests
