[package]
name = "wasm_test"
version = "0.1.0"
authors = ["nielsdos <7771979+nielsdos@users.noreply.github.com>"]
edition = "2018"

[profile.release]
lto = true
opt-level = "s"

[dependencies]
cranelift-codegen = "0.28.0"
cranelift-native = "0.28.0"
cranelift-wasm = "0.28.0"
