[package]
name = "kernel"
version = "0.1.0"
authors = ["nielsdos <7771979+nielsdos@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

#[profile.dev]
#lto = true

[profile.release]
lto = true
opt-level = "s"

[dependencies]
volatile = "^0.2.6"
spin = "^0.5.0"
bit_field = "^0.9.0"
bitflags = "^1.0.4"
multiboot2 = "^0.7.1"

[dependencies.lazy_static]
version = "^1.3.0"
features = ["spin_no_std"]
