#!/bin/sh

run_test() {
	printf "\033[1;33mRunning test $1\033[0m\n"
	make iso CARGOFLAGS="--features integration-test,$1"

	if [ $? -ne 0 ]; then
		printf "\033[1;31mCompile failed\033[0m\n"
		exit 1
	fi

	qemu-system-x86_64 -m 128 -device isa-debug-exit,iobase=0xf4,iosize=0x04 -cdrom build/img.iso --serial mon:stdio --display none

	if [ $? -ne 1 ]; then
		printf "\033[1;31mTest $1 failed\033[0m\n"
		exit 1
	else
		printf "\033[1;32mTest $1 succeeded\033[0m\n"
	fi
}

run_test 'test-mem'
